//! Build script: optionally embed the built web UI (`ui/dist`) into the server binary.
//!
//! This is what makes the production story a **single self-contained `.exe`**: the UI is
//! compiled into the binary via `include_bytes!`, so at runtime the server needs no
//! `ui/dist` folder on disk and no browser-side bundling. A non-technical user just
//! double-clicks the exe.
//!
//! If `ui/dist` is absent (e.g. a dev checkout that hasn't run `npm run build`), the
//! generated module is empty (`EMBEDDED == false`) and the server falls back to serving
//! from disk + a placeholder page — so `cargo build`/`cargo test` never break when the UI
//! hasn't been built.
//!
//! Run the production build with `scripts/build-release.ps1` (or: build the UI, then
//! `cargo build --release -p server`).

use std::path::{Path, PathBuf};

fn main() {
    // ui/dist relative to this crate (crates/server/../../ui/dist).
    let dist = Path::new("../../ui/dist");

    // Collect (web path, absolute file path) pairs for every file under ui/dist.
    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        walk(dist, dist, &mut files);
    }

    // Emit a module with a lookup + a boolean so the server knows which mode to run in.
    let mut code = String::new();
    code.push_str("// GENERATED by build.rs — do not edit.\n");
    code.push_str("pub const EMBEDDED: bool = ");
    code.push_str(&format!("{};\n", !files.is_empty()));
    if files.is_empty() {
        // No embedded UI: return None directly. Generating a single-arm
        // `match path { _ => None }` here would trip clippy::match_single_binding
        // under `-D warnings` on a clean checkout (where ui/dist is absent).
        code.push_str("pub fn embedded(_path: &str) -> Option<&'static [u8]> {\n");
        code.push_str("    None\n");
        code.push_str("}\n");
    } else {
        code.push_str("pub fn embedded(path: &str) -> Option<&'static [u8]> {\n");
        code.push_str("    match path {\n");
        for (web, abs) in &files {
            // include_bytes! resolves relative to the *generated file's* dir (OUT_DIR), so
            // the path must be absolute. build.rs runs with cwd = the crate dir.
            let cwd = std::env::current_dir().expect("current dir");
            let absolute = cwd.join(abs);
            let abs = absolute.to_string_lossy().replace('\\', "/");
            code.push_str(&format!(
                "        {:?} => Some(include_bytes!({:?})),\n",
                web, abs
            ));
        }
        code.push_str("        _ => None,\n");
        code.push_str("    }\n");
        code.push_str("}\n");
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    std::fs::write(Path::new(&out_dir).join("generated_assets.rs"), code)
        .expect("write generated assets");

    // Rebuild when the UI changes.
    println!("cargo:rerun-if-changed=../../ui/dist");
    for (_, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
    }
}

/// Recursively walk `root`, filling `out` with (web path relative to root, absolute path).
fn walk(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            walk(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            let web = rel.to_string_lossy().replace('\\', "/");
            out.push((web, path));
        }
    }
}
