[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
be-search = { path = "../be-search" }
be-biome = { path = "../be-biome" }
be-struct = { path = "../be-struct" }
cubiomes-sys = { path = "../cubiomes-sys" }
serde = { workspace = true }
serde_json = { workspace = true }
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["fs", "cors"] }
image = { version = "0.25", default-features = false, features = ["png"] }
futures = "0.3"
async-stream = "0.3"

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }

[[bin]]
name = "server"
path = "src/main.rs"
